dumpscript:
  nameOverride: "dumpscript"
  fullnameOverride: "dumpscript"

  image:
    repository: ghcr.io/cloudscript-technology/dumpscript
    pullPolicy: IfNotPresent
    # Default is the chart appVersion
    tag: ""

  databases:
  - type: postgresql
    version: "16"
    periodicity:
    - type: daily
      retentionDays: 7
      schedule: "0 1 * * *" # Every day at 1am
    - type: weekly
      retentionDays: 30
      schedule: "0 2 * * 0" # Every monday at 2am
    - type: monthly
      retentionDays: 365
      schedule: "0 3 1 * *" # Every first day of the month at 3am
    connectionInfo:
      secretName: database-secret
    aws:
      region: "us-east-1"
      bucket: "my-bucket-name"
      bucketPrefix: "my-database-name"
    extraArgs: "--format plain --encoding UTF8"

  notifications:
    slack:
      enabled: false
      webhookUrl: "https://hooks.slack.com/services/path/to/your/webhook"
      channel: "my-alerts-channel"
      username: "Dumpscript Bot"
      notifyOnSuccess: true

  serviceAccount:
    create: true
    automount: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<aws-account-id>:role/<role-name>"
    name: "dumpscript"
    namespace: "dumpscript"
