FROM alpine:3.20

RUN apk add --no-cache \
    postgresql15-client \
    mysql-client \
    aws-cli \
    jq \
    gzip \
    bash

ENV PATH="/usr/bin:${PATH}"

COPY ../scripts/restore_db_from_s3.sh /usr/local/bin/restore_db_from_s3.sh
RUN chmod +x /usr/local/bin/restore_db_from_s3.sh

ENTRYPOINT ["/usr/local/bin/restore_db_from_s3.sh"]