dumpscript:
  nameOverride: "dumpscript"
  fullnameOverride: "dumpscript"

  image:
    repository: ghcr.io/cloudscript-technology/dumpscript
    pullPolicy: IfNotPresent
    # Default is the chart appVersion
    tag: ""

  databases:
  - type: postgresql
    version: "16"
    periodicity: daily
    retentionDays: 7
    connectionInfo:
      host: "my-host"
      port: 5432
      username: "my-username"
      password: "my-password"
      database: "my-database-name"
    aws:
      region: "us-east-1"
      bucket: "my-bucket-name"
      bucketPrefix: "my-database-name"
    schedule: "0 2 * * *" # Every day at 2am
    extraArgs: "--format plain --encoding UTF8"

  serviceAccount:
    create: true
    automount: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<aws-account-id>:role/<role-name>"
    name: "dumpscript"
    namespace: "dumpscript"
