apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dumpscript-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dumpscript-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dumpscript-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dumpscript-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "dumpscript-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          image: {{ include "dumpscript-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/manager"]
          args:
            - --health-probe-bind-address=:8081
            {{- if .Values.leaderElect }}
            - --leader-elect
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:{{ .Values.metrics.service.port }}
            - --metrics-secure
            {{- end }}
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: https
              containerPort: {{ .Values.metrics.service.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet: {path: /healthz, port: health}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet: {path: /readyz, port: health}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
