{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dumpscript-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dumpscript-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: https
      port: {{ .Values.metrics.service.port }}
      protocol: TCP
      targetPort: https
  selector:
    {{- include "dumpscript-operator.selectorLabels" . | nindent 4 }}
{{- end -}}
