apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: database-secret
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: database-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: external-database-secret-key